name: Lint and Format (using Prettier) on GitHub Pull Request from any feature branch to Main

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build a Docker image
        run: docker build -t gatherly -f Dockerfile.dev .

      - name: Start a Docker container based on the Docker image, then run linting and formatting checks via that container, and finally, stop the container
        # run: docker run --rm gatherly npm run lint && npm run format
        # Now using "npx prettier --write ." as a workaround in the "docker run" command below, rather than "npm run format" (as per the commented out original "docker run" command above).
        # This is to avoid the "sh: 1: prettier: not found - Error: Process completed with exit code 127" error during GitHub Action checks in our GitHub pull requests.
        run: docker run --rm gatherly npm run lint && npx prettier --write .
